module.exports = {
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  S3_IMAGE_BUCKET: process.env.AWS_BUCKET,
  S3_EXPIRE_SECONDS: 60 * 5,
};
